export const QUOTES: string[] = [
  "A good heart 'is worth gold.",
  "To be, or not to be: that is the question.",
  "Some are born great, some achieve greatness, and others have greatness thrust upon them.",
  "We know what we are, but know not what we may be.",
  "Sweet are the uses of adversity which, like the toad, ugly and venomous, wears yet a precious jewel in his head.",
  "Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.",
  "Give every man thy ear, but few thy voice.",
  "Uneasy lies the head that wears the crown.",
  "I am not bound to please thee with my answer.",
  "A fool thinks himself to be wise, but a wise man knows himself to be a fool.",
  "Cowards die many times before their deaths; the valiant never taste of death but once.",
  "There’s many a man has more hair than wit.",
  "I dote on his very absence.",
  "Is it not strange that desire should so many years outlive performance?",
  "Better a witty fool than a foolish wit.",
  "My pride fell with my fortunes.",
  "I will praise any man that will praise me.",
  "Lord, what fools these mortals be!",
  "O thou invisible spirit of wine, if thou hast no name to be known by, let us call thee devil.",
  "Life is as tedious as twice-told tale, vexing the dull ear of a drowsy man.",
  "He that loves to be flattered is worthy o’ the flatterer.",
  "Misery acquaints a man with strange bedfellows.",
  "God has given you one face, and you make yourself another.",
  "I had rather hear my dog bark at a crow, than a man swear he loves me.",
  "I wish my horse had the speed of your tongue.",
  "How art thou out of breath when thou hast breath to say to me that thou art out of breath?",
  "Love is not love which alters when it alteration finds.",
  "Love is merely a madness.",
  "For you, in my respect, are all the world.",
  "Speak low, if you speak love.",
  "Love comforteth like sunshine after rain.",
  "For which of my bad parts didst thou first fall in love with me?",
  "Love sought is good, but given unsought, is better.",
  "The course of true love never did run smooth.",
  "Love alters not with his brief hours and weeks, but bears it out even to the edge of doom.",
  "In black ink my love may still shine bright.",
  "Love is a smoke made with the fume of sighs.",
  "And yet, to say the truth, reason and love keep little company together nowadays.",
  "Don’t waste your love on somebody, who doesn’t value it.",
  "Love is too young to know what conscience is.",
  "Do not swear by the moon, for she changes constantly. Then your love would also change.",
  "Kindness in women, not their beauteous looks, shall win my love.",
  "Love all, trust a few, do wrong to none.",
  "Self-love, my liege, is not so vile a sin, as self-neglecting.",
  "A young woman in love always looks like patience on a monument smiling at grief.",
  "If we are true to ourselves, we can not be false to anyone.",
  "Be great in act, as you have been in thought.",
  "Suspicion always haunts the guilty mind.",
  "All things are ready, if our mind be so.",
  "Many a true word hath been spoken in jest.",
  "For sweetest things turn sourest by their deeds.",
  "The Devil hath power to assume a pleasing shape.",
  "Thought is free.",
  "Our bodies are our gardens to the which our wills are gardeners.",
  "The tempter or the tempted, who sins most?",
  "He jests at scars that never felt a wound.",
  "Et tu, Brute?",
  "Conscience doth make cowards of us all.",
  "One may smile, and smile, be a villain.",
  "Look like the innocent flower, but be the serpent under it.",
  "Brevity is the soul of wit.",
  "Life’s but a walking shadow, a poor player, that struts and frets his hour upon the stage, and then is heard no more.",
  "Better three hours too soon than a minute too late.",
  "Expectation is the root of all heartache.",
  "What’s done can’t be undone.",
  "Nothing can come of nothing.",
  "No legacy is so rich as honesty.",
  "This above all; to thine own self be true.",
  "I wasted time, and now doth time waste me.",
  "The devil can cite Scripture for his purpose.",
  "What is past is prologue.",
  "Sweet mercy is nobility’s true badge.",
  "In time we hate that which we often fear.",
  "Boldness be my friend.",
  "Wisely, and slow. They stumble that run fast.",
  "Words without thoughts never to heaven go.",
  "Such as we are made of, such we be.",
  "Reputation is an idle and most false imposition; oft got without merit, and lost without deserving.",
  "All that glisters is not gold.",
  "When words are scarce they are seldom spent in vain.",
  "Pleasure and action make the hours seem short.",
  "There is nothing either good or bad, but thinking makes it so.",
  "What's in a name? That which we call a rose by any other word would smell as sweet…",
  "All the world's a stage, and all the men and women merely players.",
  "The robbed that smiles, steals something from the thief."
];

export const PICTURES: string[] = [
  "pictures/1.jpg",
  "pictures/2.jpg",
  "pictures/3.jpg",
  "pictures/4.jpg",
  "pictures/5.jpg",
  "pictures/6.jpg",
  "pictures/7.jpg",
  "pictures/8.jpg",
  "pictures/9.jpg",
  "pictures/10.jpg",
  "pictures/11.jpg",
  "pictures/12.jpg",
  "pictures/13.jpg",
  "pictures/14.jpg",
  "pictures/15.jpg",
  "pictures/16.jpg",
  "pictures/17.jpg",
  "pictures/18.jpg",
  "pictures/19.jpg",
  "pictures/20.jpg",
  "pictures/21.jpg",
  "pictures/22.jpg",
  "pictures/23.jpg",
  "pictures/24.jpg",
  "pictures/25.jpg",
  "pictures/26.jpg",
  "pictures/27.jpg",
  "pictures/28.jpg",
  "pictures/29.jpg",
  "pictures/30.jpg",
]
